<div class="panel panel-success">
    <div class="panel-heading">
        <h3 class="panel-title">
            <?=translate('title.best.team')?>
            <span class="pull-right"><strong><?= translate('total.points') ?></strong><span
                    class="badge alert-success"><?= !empty($bestTeam['points']) ? $bestTeam['points'] : 0 ?></span></span>
        </h3>
    </div>
    <div class="panel-body">
        <?php if (!empty($bestTeam['team'])) : ?>
            <p>
                <strong><?= translate('points.stage') ?></strong>: <?= $bestTeam['stage'] ?>
            </p>
            <?php foreach ($bestTeam['team'] as $key => $value) : ?>
                <p>
                    <strong><?= translate('points.' . $key) ?></strong>: <?= $value ?>
                </p>
            <?php endforeach; ?>
        <?php else : ?>
            <div class="alert alert-danger">
                <strong><?= translate('alert.error') ?></strong><?=translate('error.no.best.team.found')?>
            </div>
        <?php endif; ?>
    </div>
</div>